basic_settings:
  site_title: Would Productions
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Projects'
      url: '/'
    - title: 'News'
      url: '/blog/'
    - title: 'Us'
      url: '/about/'
    - title: 'Contact'
      url: '/contact'

footer_settings:
  logo_image: /images/favicon.png
  logo_width: 50
  footer_tagline: 

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/f/xrgrjbwo'
  confirmation_url: '/thanks'
  email_subject: 'Would Productions contact form submission'
  send_button_text: 'Send'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: 'https://www.youtube.com/playlist?list=PLQ2ZWyzK5zqzdqIPFqV9wZzNNXs-Y3WVW'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#000000'
  background_alt_color: '#000000'
  text_dark_color: '#ffffff'
  text_medium_color: '#D3D3D3'
  text_light_color: '#808782'
  accent_color: 'whitesmoke'
  border_color: '#ffffff'
  overlay_background_color: '#000000'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#313639'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Nanum Myeongjo:300,400,600,700" rel="stylesheet">'
  title_font: '"Nanum Myeongjo", sans-serif'
  body_font: '"Capriola", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 550
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""